Delete killall-g.sh
openaps/oref0 pull request #1426
Opened 2022-02-21 09:19 UTC by Angelica421

2022-02-21 22:01 UTC, scottleibrand commented
Why?

2022-02-28 04:27 UTC, Angelica421 reviewed
True

2022-02-28 05:43 UTC, scottleibrand commented
Why are you proposing to delete this file?

2022-02-28 05:44 UTC, scottleibrand requested changes
This kind of change needs significantly more explanation, testing, etc.

2022-02-28 05:49 UTC, closed without merging